# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
---
apiVersion: v1
kind: Template
metadata:
  name: lightwell-experience-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: lightwell-experience
    spec:
      feoConfigEnabled: true
      # TODO: add serviceTiles and searchEntries for lightwell
      API:
        versions:
          - v1
      envName: ${ENV_NAME}
      title: LightwellExperience
      deploymentRepo: https://github.com/lightwell-experience/lightwell-experience-frontend
      frontend:
        paths:
          - /apps/lightwell-experience
      image: ${IMAGE}:${IMAGE_TAG}
      pushCacheEnabled: true

      module:
        manifestLocation: '/apps/lightwell-experience/fed-mods.json'
        modules:
          - id: 'lightwell-experience'
            module: './RootApp'
            routes:
              - pathname: /lightwell-next # temporary onboarding route
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/lightwell-network-ui-tenant/lightwell-network-ui/lightwell-network-ui-frontend
